### ISSUE TITLE
Receipt validation example

### ISSUE THREAD

**Issue by subsoap** [WICG/webmonetization#132]
I can't find an example of doing receipt validation. For example, Coil payments to an Uphold pointer.

**Comment by subsoap** [comment]
Here is some receipt validation related info but honestly it's still ??? to me.

https://forum.defold.com/t/we-are-hosting-a-web-monetization-game-jam/66474/26

**Comment by melissahenderson** [comment]
We've created https://webmonetization.org/docs/receipt-verifier/
