### ISSUE TITLE
CSP issues with <script>${documentMonetizationPolyfill}</script> injection

### ISSUE THREAD

**Issue by sublimator** [WICG/webmonetization#137]
See: https://github.com/coilhq/web-monetization-projects/issues/1248

- [ ] publish a new version of the extension/add-on that sends the messages as expected.  
- [ ] update the documentation with the CSP workaround of including the polyfill

**Comment by wmurphyrd** [comment]
I published a [web-monetization-polyfill](https://www.npmjs.com/package/web-monetization-polyfill) package on NPM, so documenting the use of the polyfill can be just `require('web-monetization-polyfill')`. Looking forward to the release!

**Comment by sublimator** [comment]
Nice! Thanks @wmurphyrd :)

**Comment by adrianhopebailie** [comment]
@sublimator what's the status on this issue?

**Comment by sublimator** [comment]
We should be publishing 0.0.52 soonish, with the new single polyfill 
Have been keeping @wmurphyrd in the loop 
You probably don't need to worry about it for your WM v2 issue roundup

**Comment by marcoscaceres** [comment]
Duplicate of #29
