### ISSUE TITLE
How can a website know when monetization with the current payment pointer is failing

### ISSUE THREAD

**Issue by dellagustin** [WICG/webmonetization#144]
Hello all,

I could not find in the Javascript API description how a client can be informed if the payment to a pointer is failing.
This is specially needed for revenue sharing with 3rd parties (i.e. a podcast player that share revenue with podcast authors).
If I use [probabilistic revenue sharing](https://webmonetization.org/docs/probabilistic-rev-sharing), and the monetization is failing for the selected pointer, I will likely update the meta tag with the pointer of another party, instead of not monetizing at all.

This is somewhat related to #18

**Comment by sublimator** [comment]
Should there perhaps be error events ?

**Comment by dellagustin** [comment]
@sublimator , yes I think so.

**Comment by adrianhopebailie** [comment]
@dellagustin can you describe the scenario in some more detail.

I assume that you mean the website has received at least one monetizationprogress event but that these stop

OR the issuea scenario where the browser is attempting to pay the payment pointer but the payments are failing (no monetizationstarted or monetizationprogress events) and this is indistinguishable from a user that does not have monetization enabled

**Comment by mankins** [comment]
@dellagustin Something like:

```
 document.monetization.addEventListener('monetizationerror', (error) => {
        console.log({error});
      })
```

?

**Comment by dellagustin** [comment]
Hello @adrianhopebailie , I am thinking more about cases where the website is setting the payment pointer to 3rd parties, specially when using revenue sharing. If the payment pointer of a 3rd party cannot receive payments, then the website will want to set another payment pointer if possible, os that the content does not go unmonetized.

Most likely in this cases I think browser is attempting to pay but failing.

@mankins your proposal looks ok to me.

**Comment by sharafian** [comment]
It might make sense to make this an `error` boolean on the monetizationprogress event, similar to `finalized`.
