### ISSUE TITLE
When should the browser fetch the content of payment pointer?

### ISSUE THREAD

**Issue by sidvishnoi** [WICG/webmonetization#149]
**Page load**: Should the browser fetch content at the monetization tag (or, payment pointer/SPSP endpoint) after consulting with WM agent that a payment can be made or, fetch first then try payment?

**Visibility Change:** If a user goes from tab A to B and back to tab A, should the browser fetch the content again, or store the response until a tab is closed?

**Comment by sublimator** [comment]
Maybe this should depend upon cache settings communicated in (standard HTTP) headers from the SPSP response ?

Other than that, I can say that the current extension queries the SPSP endpoint every time a STREAM is setup, which includes retries after failures, and "resuming" upon visibility changes.

**Comment by sidvishnoi** [comment]
Cache HTTP headers are to be respected when fetching. Here, we're trying to understand when should fetch happen. Can we avoid a re-fetch on visibility change if the response is supposed to be valid for given duration (with or without Cache HTTP header)? Retry on failure/expire definitely needs a re-fetch.

One thing to note here is we can fetch multiple times in the same session (tokens expired, visibility change etc.), which is different from how other fetches happen in HTML (once on page load). This could be a signal that `<link>` is not as semantic (or appropriate for this use case) as we discussed in https://github.com/WICG/webmonetization/issues/19.

**Comment by adrianhopebailie** [comment]
IMO the browser should fetch the Payment Pointer resource first as soon as it parses the tag in the page and should not fetch it again unless payments fail.

The browser should also respect cache headers.

**Comment by sharafian** [comment]
We need to take our privacy model into account here. Right now we re-fetch the ILP address whenever we use a new privacy token so that privacy tokens are never associated by sending to the same ILP address.

However we've been discussing whether it might be acceptable to use several privacy tokens for the same ILP address as the only thing it would (seem to) reveal is the length of a page session. https://github.com/coilhq/web-monetization-projects/issues/1459

**Comment by sublimator** [comment]
@sharafian @adrianhopebailie 

Any comment re: 
> This could be a signal that <link> is not as semantic (or appropriate for this use case) as we discussed in #19.

?

**Comment by sublimator** [comment]
> All other link tags are fetched only once - that is on page load. That's when
their onload event is fired. As of now, there's no other link tag that can fetch
the resource again in without any change (change in href value that is) in the
tag. So, it might mean browsers don't have that machinery to reload as well

Above from @sidvishnoi

**Comment by sidvishnoi** [comment]
I went to research more about this. From the [HTML spec for link[rel=manifest]](https://html.spec.whatwg.org/multipage/links.html#link-type-manifest:fetch-and-process-the-linked-resource):

> The appropriate time to fetch and process the linked resource for this link type is when the user agent deems it necessary. For example, when the user chooses to install the web application.

It's not all fetch once on page load apparently. There is also not a one-to-one mapping of these algorithms in browser implementations, so it should be possible (ideally) to re-run fetch steps as needed. Might not be a thing to worry about.

**Comment by adrianhopebailie** [comment]
@sidvishnoi What is the conclusion?

I think we're saying:
- The UA does the SPSP query once on page load and respects cache control headers
- If WM is stopped and then restarted the existing connection will be re-used
- If there is an error then the SPSP query is repeated

**Comment by sidvishnoi** [comment]
> The UA does the SPSP query once on page load and respects cache control headers

Agree.

> If WM is stopped and then restarted the existing connection will be re-used

This is the pause/resume behavior, and not stop/start behavior, right?

> If there is an error then the SPSP query is repeated

With the proposed WebExt API, when extension explicitly requests a refresh (as it sees fit  due to error or other reasons), should the browser still respect the `cache-control` or bypass cache? i.e. browser finds cached result is not stale, so returns same result vs. browser returns different result if a refresh is explicitly requested.

**Comment by adrianhopebailie** [comment]
> This is the pause/resume behavior, and not stop/start behavior, right?

Yes.

> With the proposed WebExt API, when extension explicitly requests a refresh (as it sees fit due to error or other reasons), should the browser still respect the cache-control or bypass cache?

I would agree that bypass cache is correct. Is there potential for this to be abused?

**Comment by adrianhopebailie** [comment]
To clarify, the scenario here is that the SPSP server has sent cache headers indicating the response is still valid but when the sender tries to use the ILP address and secret from the response it gets an error.

This implies an error on the server so it seems like the best course of action is to bypass the cache and request new ILP address and secret.

**Comment by sidvishnoi** [comment]
> Is there potential for this to be abused?

Not sure TBH. It's essentially same as refreshing of a website repeatedly that implements cache-control poorly, so mostly degraded performance and wasted browser cache storage. SPSP server might start throttling requests from given origin before that.

**Comment by marcoscaceres** [comment]
In #193, when the `link` element loads and processes the SPSP, it then fires a "load" event. That gives enough details to answer the "monetization is supported and things got set up". 

If money actually starts coming trough is an entirely different concern, which is ok (and not something the API can answer).

**Comment by marcoscaceres** [comment]
In #193, they just load on page load. There are a bunch of additional rules defined, but it's basically the same as loading a CSS file. Developers can then disable `<link>` by doing various things... like adding a `disabled` attribute, removing "href=", etc.

**Comment by sublimator** [comment]
> In https://github.com/WICG/webmonetization/pull/193, they just load on page load.

or upon tag insertion/reconfiguration thereafter 

> it's basically the same as loading a CSS file

This won't work for receipts at the least (even though they are long due to be deprecated) and doesn't really map well to how we request the connection details (or use the url for them) in actual practice. 

So the question as to whether link tags will/should support re-requests is still open
