### ISSUE TITLE
Should WM Senders know origin of the monetized website?

### ISSUE THREAD

**Issue by adrianhopebailie** [WICG/webmonetization#15]
From web-monetization created by [adrianhopebailie](https://github.com/adrianhopebailie): adrianhopebailie/web-monetization#10  

See question in the [sending](https://webmonetization.org/docs/sending.html) explainer around sharing of the website origin.

The WM Sender is a implemented as a Payment Handler which handles a `PaymentRequestEvent` for each payment that it must send.

Currently that event provides the origin of the calling website however that is intended to be a website that created a `PaymentRequest` not a website that is being monetized.

In the case of monetization, does the Payment Handler need this information (for example to ensure it is not sending money to banned websites) or can it entirely trust the WM Agent's decisiuon about which websites to pay and how much?

**Comment by marcoscaceres** [comment]
Closing... as this won't be using payment handler, etc... what information is shared between the site and WM is controlled by the link element.
