### ISSUE TITLE
Broken link to wallets at https://webmonetization.org/docs/getting-started/

### ISSUE THREAD

**Issue by jasikpark** [WICG/webmonetization#154]
The file links to `./ilp-wallets` which gets rendered as https://webmonetization.org/docs/getting-started/ilp-wallets rather than https://webmonetization.org/docs/ilp-wallets

**Comment by melissahenderson** [comment]
This is so odd. It works on my phone but not on my computer. I'll get it fixed.

**Comment by melissahenderson** [comment]
I've made updates to the links on the Getting Started and Glossary pages that should fix the issue. I'll give it a day or so to make sure, then update the format of the rest of the links on the site. Leaving this open for now.

**Comment by jasikpark** [comment]
Great! - the links are working for me now
