### ISSUE TITLE
Should websites know if user can make payment?

### ISSUE THREAD

**Issue by sidvishnoi** [WICG/webmonetization#159]
Presently, the only way to know if a user can make payment is to timeout against "monetizationprogress" or "monetizationstart" not being fired. Should there be a way for websites to know if payment can be made? This will let websites to act more quickly to use any alternatives.

```
CanMakePayment() = (
  a valid monetization tag exists
  AND browser extension/payment handler is installed
  AND user is authenticated
  AND_MAYBE user has enough balance
)
```

Also, CanMakePayment != WillPay.

**Comment by sidvishnoi** [comment]
Note: This is pretty similar to `document.monetization.state = "pending"` (forgot it exists):
> The extension is trying to send payments but has yet to send the first non-zero micropayment.

I was thinking something like:
```js
if (await monetization.canMakePayment()) {
  monetization.addEventListener("progress", callback);
} else {
  fallback();
}
```
.. as the API (instead of monetization.state, start/stop/pending events). `canMakePayment()` kinda also parallels with the PaymentRequest API.

**Comment by adrianhopebailie** [comment]
Is this a privacy concern? What if a website knows a user CAN pay but doesn't?
I think we concluded previously that we'd like users that refuse to pay to appear the same as users that don't have WM enabled.

**Comment by sidvishnoi** [comment]
>  if a website knows a user CAN pay but doesn't

That could possibly mean user/WM agent has blocked the website, OR user doesn't have enough balance OR user is not authenticated. If a website asks user to "unblock" (like they do for ad-blocks) when there can be other multiple reasons other reason, then it's bad case on websites.

I think `canMakePayment()` can include "a browser extension/payment handler is installed" without any privacy concerns.

>  I think we concluded previously that we'd like users that refuse to pay to appear the same as users that don't have WM enabled.

Is there a public discussion on this? I may be missing some context.

**Comment by sharafian** [comment]
In the case where the user is logged out, or their WM provider subscription no longer works, or they have blocked the website, `monetizationpending` really shouldn't be emitted. In theory `canMakePayment` should be equivalent to 

```js
document.monetization && (document.monetization.state === "pending" || document.monetization.state === "started")
```

**Comment by marcoscaceres** [comment]
In #193, when the link element loads and processes the SPSP, it then fires a "load" event. That gives enough details to answer the "monetization is supported and things got set up".

If money actually starts coming trough is an entirely different concern, which is ok (and not something the API can answer).
