### ISSUE TITLE
Privacy section

### ISSUE THREAD

**Issue by franziskuskiefer** [WICG/webmonetization#165]
I see privacy being mentioned in a couple issues here as a reason to do or not to do certain things. The spec however doesn't mention privacy at all. I think the spec would benefit from a privacy section explaining the privacy model, measures taken to protect user privacy, as well as limitations.

**Comment by marcoscaceres** [comment]
There are certainly going to be a lot of questions around what gets passed over to the network by the monetization agent - and about the privacy and security characteristics of the Interledger network. 

We probably need pretty strict guidelines around that, particularly about fetching the dereferenced payment pointers.
