### ISSUE TITLE
Indicate failure reasons from WM Sender

### ISSUE THREAD

**Issue by adrianhopebailie** [WICG/webmonetization#18]
From web-monetization created by [adrianhopebailie](https://github.com/adrianhopebailie): adrianhopebailie/web-monetization#13  

Do we need to indicate WHY a payment failed if it did? 

Maybe an error code?

Can the Payment Handler simply `respondWith()` an ILP reject packet and let the browser infer the failure reason from the `code`? 

A possible failure case is that the browser requests the sender to send in a currency it can't convert from.

1. The browser calculates a monetization rate for a site and invokes the sender requesting it make a payment of USD 0.0004
2. The user's account at the sender is denominated in EUR
3. The sender determines that it can't calculate the appropriate amount to send in EUR

Is [F03 - Invalid Amount](https://interledger.org/rfcs/0027-interledger-protocol-4/#error-codes) error appropriate here?

**Comment by AlexLakatos** [comment]
We've got around to the idea that even if we surfaced ILP reject packets, a web developer couldn't do anything about fixing them. So we're defaulting to surface the SPSP error, because a web developer could do something about that (i.e. change the payment pointer).
