### ISSUE TITLE
[Meta] Project coordination

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/webmonetization#212]
Hey crew! as we start making more changes to the spec over next few months, we could really use some help making sure everything stays in sync. I'm wondering:  

Who will be responsible for: 
 * the Website - Including making sure dependencies are up to date and deployments happen.  
 * updating the docs.  
 * reaching out to plugin/web-component implementers - letting folks know what's changed. 

We can set up a Github template to help with this... at least, we can make sure tasks are done before we merge anything into the spec.

**Comment by marcoscaceres** [comment]
@melissahenderson, are you still able to help us with the updating the docs?

**Comment by marcoscaceres** [comment]
Hopefully not many... maybe 1 hour max?... probably around 30 minutes.

**Comment by melissahenderson** [comment]
That should be fine.

**Comment by marcoscaceres** [comment]
Closing as answered.
