### ISSUE TITLE
Add example of how to verify a receipt 

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/webmonetization#237]
It would be great if the spec or an explainer had some code that showed how to verify a receipt... and what information is contained in the receipt (i.e., is it JSON? what's the spec that has that?).

**Comment by sublimator** [comment]
The og issue:
https://github.com/interledger/rfcs/issues/568

@wilsonianb

**Comment by sublimator** [comment]
And the implementing PR
https://github.com/interledger/rfcs/pull/570

**Comment by marcoscaceres** [comment]
Thanks @sublimator! @AlexLakatos also pointed me to:  
https://webmonetization.org/docs/receipt-verifier

We should have a simple example of this in the spec.

**Comment by pp-koch** [comment]
The documentation will not treat this topic, mostly because I do not understand it. It will just link to the webmonetization.org page.

**Comment by marcoscaceres** [comment]
No problem. I'm happy to add it to the spec based on the docs above. Maybe after I can get you check it to see if it makes sense?
