### ISSUE TITLE
URL of new spec?

### ISSUE THREAD

**Issue by pp-koch** [WICG/webmonetization#242]
What will, eventually, be the URL of the new spec and when will it appear there? I have to link to it from my documentation.

**Comment by marcoscaceres** [comment]
See link in #193

**Comment by pp-koch** [comment]
But this is not the final URL, right? My question was more: how long will it take to publish the spec on webmonetization.org or another more official site?

**Comment by marcoscaceres** [comment]
ah, got it... we first need to update all the documentation on webmonetization.org to match #193. Once all that's updated, we can merge #193. We are aiming at around 6 weeks? (although xmas might make that challenging)

**Comment by pp-koch** [comment]
Ah, so it's waiting for my documentation. OK, clear.

I'd better get writing then.

**Comment by marcoscaceres** [comment]
heh, yes (updating the contents of this repo would be great)... but also, we are making sure what's in #193 is "sane" and actually works.

**Comment by pp-koch** [comment]
I have to write it all down before I know what makes sense and what doesn't. But it's now mostly a case of re-ordering bits of documentation I already have. The load event is the only real newcomer.

**Comment by marcoscaceres** [comment]
Just want to be super clear. The blocker for merging is updating all of these files:
https://webmonetization.org/docs/getting-started

Not sure who is updating all of those right now - but @AlexLakatos will let us know.

**Comment by huijing** [comment]
Resolved by #193
