### ISSUE TITLE
allow attribute and fetch/process

### ISSUE THREAD

**Issue by pp-koch** [WICG/webmonetization#244]
In the list under "The appropriate times to fetch and process this type of link is: "

Shouldn't we also mention the allow attribute of an iframe being changed? I mean, if allow="monetization" is removed the monetization stream should end, right?

**Comment by marcoscaceres** [comment]
Need to check. I’m not sure what happens if allow= is dynamically updated… but you are likely right.

**Comment by sublimator** [comment]
It does in current extension

**Comment by marcoscaceres** [comment]
Note to self, integrate with "container policy":
https://w3c.github.io/webappsec-permissions-policy/#container-policy

HTML says that changing it after the document has loaded has no effect: 
<img width="1070" alt="Screen Shot 2021-12-08 at 4 27 11 pm" src="https://user-images.githubusercontent.com/870154/145153389-8053ef2b-cd68-49a1-85d8-306f4d2522fe.png">

**Comment by marcoscaceres** [comment]
Just noting that the current spec does do the "allowed to use" check.

**Comment by huijing** [comment]
Add note to https://webmonetization.org/specification.html#permissions-policy

> The allow attributes only take effect when the content navigable of the iframe is navigated. Adding or removing the monetization attribute has no effect on an already-loaded document.
