### ISSUE TITLE
The debugging flags

### ISSUE THREAD

**Issue by pp-koch** [WICG/webmonetization#245]
Will the debugging flags continue to exist? In the old one they were:

localStorage.setItem('WM_DEBUG',true) for general debugging, but not the monetizationprogress event

localStorage.setItem('WM_DEBUG_PROGRESS',true) for the monetizationprogress event

localStorage.setItem('WM_POINTER_PROPERTY',true) to temporarily enable navigator.monetization.pointer = settable

I assume the third one will go away and the first one will remain. What about the monetization events? Will they retain a separate flag? Since they're the only thing left in the spec that web developers really need to monitor I propose that we do not retain a separate flag, but instead fold them into WM_DEBUG.

**Comment by marcoscaceres** [comment]
Underlying this, should we specify a testing mode? 

Basically, it should be a specifically crafted SPSP JSON file or a special URL. 

That URL would load and cause “monetization” events to fire periodically. 

On the other hand, it would be pretty simple to mock all this with custom events.

**Comment by pp-koch** [comment]
Also, if we specify a testing mode we need a way to temporarily turn monetization off/on. Web devs will want to test in both modes. And should they be able to test as if monetization is on even when they aren't subscribed to Coil?

**Comment by huijing** [comment]
Coil extension no longer exists.
