### ISSUE TITLE
Link tags backwards compatibility 

### ISSUE THREAD

**Issue by sublimator** [WICG/webmonetization#252]
Opening this while I remember. The community will probably want some say in how the next version of the Coil extension handles existing link tags.

We've implemented <link> tags already but the new spec supports them in the body, and more than one per document. 
It also does away with document.monetization 

TODO: add details

**Comment by pp-koch** [comment]
Theoretically we could assure backward compatibility from v2 on. I mean, the link tags are not going to change, are they? They could just unlock more functionality.

**Comment by sublimator** [comment]
Well, when there are multiple tags, there is contention for
`document.monetization.state` at the least
I suppose you could just fire the events and set the state on
document.monetization for the first tag (in document order) ?

**Comment by pp-koch** [comment]
Oh, you mean for the old API? I think it should be removed before we get serious about multiple links.
