### ISSUE TITLE
[Docs] Web Monetization API - Libraries 

### ISSUE THREAD

**Issue by hajjimo** [WICG/webmonetization#263]
- [x] Section for Libraries on main page
    - Issue with current main page is that the libraries are all relevant for v1.0 only
    - We will have to keep this section like it is until there are v2.0 libraries available
- [x] Separate page with links to different libraries 
    - For now, we will duplicate the home page tools section under Resources but label them as v1.0

**Comment by huijing** [comment]
Duplicate the Web Monetization tools section under the Resources section of the docs.
