### ISSUE TITLE
Define Content Security Policy for allowed Payment Pointer origins

### ISSUE THREAD

**Issue by adrianhopebailie** [WICG/webmonetization#29]
From https://github.com/interledger/webmonetization.org/issues/14#issuecomment-541844573 originally posted by @justmoon 

... make Web Monetization part of the Content Security Policy in the future. For instance, my CSP could determine which origins I allow for payment pointers:

```http
Content-Security-Policy: default-src 'none'; monetization-src mywallet.com
```

Which would allow payment pointers starting with $mywallet.com.

**Comment by Malvoz** [comment]
Consider that someone, somewhere made the decision not to have a CSP directive govern the Payment Request API, but instead as a policy-controlled feature named [`payment`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/payment). That is why I initially proposed a Feature-Policy directive for web monetization, to align with that approach. See https://github.com/interledger/webmonetization.org/issues/28#issuecomment-541889335.

I don't think there's a need for a CSP directive if there is a FP feature...

**Comment by adrianhopebailie** [comment]
@Malvoz this is for a different purpose. This allows the site owner to define restrictions around the origins of Payment Pointers that are used.

Feature Policy would be for controlling which third-party contexts can be monetized.

Or am I misunderstanding?

**Comment by Malvoz** [comment]
A document can impose a Feature-Policy on itself, e.g. by sending along a Feature-Policy HTTP header, or [potentially](https://github.com/w3c/webappsec-feature-policy/issues/55) using a `<meta http-equiv="Feature-Policy" content="...">` element. So in that regard FP works the same as CSP.

**Comment by adrianhopebailie** [comment]
Right, but it feels like in this case we're using FP to allow (or not) monetization and CSP to specify which Payment Pointers are allowed.

**Comment by Malvoz** [comment]
That makes sense, these are 2 separate concerns. Sorry for the distraction.

**Comment by marcoscaceres** [comment]
I've added Permission Policy integration in #214, but it would make sense to also restrict the origins from which the setup JSON is sourced.

**Comment by marcoscaceres** [comment]
Noting, this would need to be added to the Fetch spec.... the WM spec could make note of it tho.

**Comment by marcoscaceres** [comment]
CSP is now defined in PR  #193
