### ISSUE TITLE
Update to Cloudflare workers wrangler v2

### ISSUE THREAD

**Issue by wilsonianb** [WICG/webmonetization#295]
Cloudflare sent this via email (I can't find a web version of it)
![Screenshot from 2023-02-08 13-12-50](https://user-images.githubusercontent.com/5885521/217629411-2d30a799-95d8-4d70-b6c6-996ea08131a7.png)

This is the linked upgrate guide
https://developers.cloudflare.com/workers/wrangler/migration/migrating-from-wrangler-1/

This likely at least involves bumping the version of the GitHub Actions workflow
https://github.com/WICG/webmonetization/blob/a95000a4bd0195a436be611966c8c5e114b4f218/.github/workflows/publish-workers.yml#L29

**Comment by huijing** [comment]
Resolved by #296
