### ISSUE TITLE
Coil is dead

### ISSUE THREAD

**Issue by faraixyz** [WICG/webmonetization#306]
From [Coil](https://web.archive.org/web/20230319161753/https://www.coil.com/):

> When we started Coil in 2018, Interledger was only an idea. Over the last five years we breathed life into the technology and sparked a vibrant ecosystem around it. Now it’s time to pass the torch to a neutral body in the form of the [Interledger Foundation](https://interledger.org/) to steward the future development of Interledger.

>
> As part of this evolution, we’ve decided to sunset Coil’s products and development efforts. On February 2, 2023, we will no longer accept sign-ups for the Coil Membership. On March 15, 2023, we will discontinue our service. More detailed information is available in our [FAQ](https://www.coil.com/#FAQs).

**Comment by justmoon** [comment]
... long live Web Monetization!

Coil founder here! Just to give some additional context:

* We're open sourcing the key parts of our Web Monetization backend such as our privacy/anonymization functionality
* Several of our engineers have moved on to the Interledger Foundation and are working on updating the browser extension and other pieces to make it easy to create a Web Monetization provider for yourself or others
* I'm personally moving on to work on [Dassie](http://dassie.land) which is a peer-to-peer implementation of Interledger

Together, the net result should be that Web Monetization is no longer this thing that only works with Coil (which was never the intent) and both WM and Interledger will be much more accessible for adoption and tinkering.
