### ISSUE TITLE
Offline monetization for PWAs

### ISSUE THREAD

**Issue by tiesselune** [WICG/webmonetization#31]
As I understand the spec, monetization is a live process depending on network connection to the website, a payment agent and a payment receiver.

Progressive Web Apps that offer real offline features might be interested in monetizing the app even if the user is offline, by tracking how much time has been spent on the app. Has this use case been considered, or has it been disregarded since offline use of PWAs can be considered exceptional?

Plus, since "offline use" could be considered a premium feature of PWAs reserved to paying users, offline time tracking and payment could be a real plus to the spec, if technically possible.

**Comment by adrianhopebailie** [comment]
> Has this use case been considered, or has it been disregarded since offline use of PWAs can be considered exceptional?

It's not being tracked so let's use this issue to do that.

> Progressive Web Apps that offer real offline features might be interested in monetizing the app even if the user is offline, by tracking how much time has been spent on the app.

The challenge is, what happens after the PWA has been used for X minutes and then goes online? How does the app prove that it's "owed" `X * normal rate` as a single payment?

We'd need to give some thought to this but historically doing anything related to payments while offline is pretty hard.

**Comment by sharafian** [comment]
The way I'd see this is that it's possible but only if the site trusts the client.

When you're offline the client can still track how long you've spent on the site, as you've pointed out. But the site obviously can't ask the server for confirmation whether the payments were sent. So if we want the site to provide some premium content then we need a way for the extension to basically have a message that says "I'm going to pay you" and you need to write the site in a way that trusts that. I think those are OK constraints.

I could think of a couple ways of implementing this

We could add a new event type that represents an intention to send money, something like "monetizationplanned." it would be very similar to the way that "monetizationprogress" functions only it just means an amount has been queued to be sent. The amount which is still pending can be determined by a site by looking at the sum of all monetizationprogress events minus the sum of all monetizationplanned events. The extension could implement some kind of queuing system that sends this planned monetization in the background once you go back on line. This does add a fair bit of complication and is a little confusing.

Another way would be to have a new monetization state, something like "offline" or "donate." This would be a way to communicate to the site that you're counting this time and will pay it out later but you can't send it right now and you can't be sure of the exact amount. A site would recognize this state and grant some features, trusting that monetization will occur in the future. This also covers a use case for WM providers that want to be a bit more in the flattr/brave style of payment, where they pay out at the end of the month.

**Comment by marcoscaceres** [comment]
If the SPSP steps set up everything even when offline (e.g., the response was cached), but payments can't come through, then it's really up to the agent to start sending payments once connection is re-established. However, the PWA itself knows that it's offline (via, for example, `navigator.online`) so it can also adapt accordingly until payment events result.

**Comment by marcoscaceres** [comment]
closing as answered
