### ISSUE TITLE
Remove the "Receipt Verifier Service", associated CF worker, and any mention of it from the docs

### ISSUE THREAD

**Issue by AlexLakatos** [WICG/webmonetization#317]
Receipts are deprecated in the new Web Monetization spec. https://webmonetization-preview.netlify.app/specification.html

We should remove the [Receipt Verifier Service](https://webmonetization.org/docs/receipt-verifier) from the CloudFlare workers, the dedicated page, and any usage of it throughout the website.

**Comment by huijing** [comment]
@AlexLakatos 
Is it sufficient to just remove the if-else at https://github.com/WICG/webmonetization/blob/71d3c878b9ab76d29d63c194e11aabc9aafdfce6/workers/exclusive-content/src/lib/requestHandlers.ts#L32 or does the entire `handleExKeyDerivation` function need to be rewritten?
