### ISSUE TITLE
Further refactoring for /meta-tag page

### ISSUE THREAD

**Issue by huijing** [WICG/webmonetization#322]
In addition to findings in https://github.com/WICG/webmonetization/issues/315#issuecomment-1576234267, we should look into:
- ~~Further validating the Payment Pointer URL~~ (upon further investigation, the definition of a valid URL only requires at least a scheme (ftp://, https://, http://) and a host name, which we currently already validate with the URL constructor)
- Change default example where you add payment pointer from `<link rel="monetization" href="$YourPaymentPointer" />` to `<link rel="monetization" href="https://YourPaymentPointer" />`
- ~~Using `$YourPaymentPointer` as a label might be a little awkward~~ (done)
- ~~Rename slug to `link-tag` and add redirect for `/meta-tag` (via CloudFlare)~~ (done)

**Comment by melissahenderson** [comment]
Can we change the default example that shows before you manually add your payment pointer from:

<link rel="monetization" href="$YourPaymentPointer" />

to

<link rel="monetization" href="https://YourPaymentPointer" />

**Comment by huijing** [comment]
> Can we change the default example that shows before you manually add your payment pointer from:
> 
> `<link rel="monetization" href="$YourPaymentPointer" />`
> 
> to
> 
> `<link rel="monetization" href="https://YourPaymentPointer" />`

Sure.
