### ISSUE TITLE
Declaritive vs Imperative API?

### ISSUE THREAD

**Issue by sharafian** [WICG/webmonetization#33]
Making a place for this question in the explainer so we can link to it

> The current proposal is for a hybrid declarative and imperative API. Websites declare their ability to accept WM payments using a <meta> tag in the page header. Imperatively, a developer can then access the global monetization object on the DOM to track incoming payments stream/events and react to these.

**Comment by michielbdejong** [comment]
IIUC "websites" and "a developer" are the same API consuming party here, to be distinguished from the other API providing party namely the browser or an installed browser extension, right?
So both IIUC there are two parts of the API:
* "can declare their ability to accept WM payments using a tag in the page header" (declarative)
* "access the global monetization object on the DOM to track incoming payments stream/events and react to these (imperative)

And both APIs are:
* provided by the browser (or extension), and
* to be used by the website / developer?

**Comment by marcoscaceres** [comment]
Yeah, it's not really a "VS" thing... the two (HTML element + JS API) compliment each other nicely. 

I'm going ahead and closing this, as it's not actionable from a spec perspective (in as far as they both are getting specified).

**Comment by Maruxy20** [comment]
<a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/3.0/88x31.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/">Licencia Creative Commons Atribución-CompartirIgual 3.0 No portada</a>.

**Comment by Maruxy20** [comment]
> [![Licencia Creative Commons](https://camo.githubusercontent.com/d26c9b568c4dac3593dc55e78e7544bedd2021bbc05bded209f874a830bcf0e4/68747470733a2f2f692e6372656174697665636f6d6d6f6e732e6f72672f6c2f62792d73612f332e302f38387833312e706e67)](http://creativecommons.org/licenses/by-sa/3.0/)Esta obra está bajo una [Licencia Creative Commons Atribución-CompartirIgual 3.0 No portada](http://creativecommons.org/licenses/by-sa/3.0/).
