### ISSUE TITLE
Use updated Payment Request and Payment Handler APIs?

### ISSUE THREAD

**Issue by sharafian** [WICG/webmonetization#34]
Making a place for this question in the explainer so we can link to it

> The Web Payments WG has designed two APIs that follow a similar pattern to Web Monetization but for a different use case.
> 
> The Payment Request API is an imperative API that websites can use to request a single discrete payment: the Payment Request API is designed to always prompt the user for authorization as part of the flow as it is designed for payment sizes where this is necessary. However, nothing prevents this API also supporting a non-interactive flow that supports Web Monetization use cases.
> 
> Further, the Payment Handler API aligns well with the model anticipated for Web Monetization senders: A sender might manifest as a specialized Payment Handler capable of returning not just a PaymentResponse but also a handle to a stream of micropayments.

**Comment by marcoscaceres** [comment]
Closing as it's addressed by: 
https://webmonetization.org/specification.html#relation-to-other-technologies
