### ISSUE TITLE
Replace circle-ci deployment with GitHub Actions

### ISSUE THREAD

**Issue by AlexLakatos** [WICG/webmonetization#360]
Circle CI is running out of memory, and failing to deploy the builds.

We should take this opportunity to swap deployments to GitHub actions.

The current setup uses the `yarn deploy` command (build the website, and commit it to the gh-pages branch, which takes care of the hosting). I think we should be able to replicate that for GitHub Actions.

**Comment by huijing** [comment]
## Notes

Netlify build took around 2min 14s.

![Screenshot 2023-07-18 at 11 19 43 AM](https://github.com/WICG/webmonetization/assets/1461498/7e5f4c27-5ab7-400b-94e8-54afe85328f4)
