### ISSUE TITLE
Glitch Clean-Up

### ISSUE THREAD

**Issue by melissahenderson** [WICG/webmonetization#372]
This issue is for cleaning up the Glitch examples for:
* [Remove ads](https://glitch.com/edit/#!/wm-ad-free-experience)
* Provide exclusive content (there's two examples for this one) ([1](https://glitch.com/edit/#!/wm-exclusive-content-basic) and [2](https://glitch.com/edit/#!/wm-exclusive-content-advanced))
  * Note that in the guides, "basic" and "advanced" are changed to "simple" and "complex"
* [Payment counter](https://glitch.com/edit/#!/wm-count-revenue)
  * Note that the guide avoids using the term "micropayment"
* [Probabilistic revshare](https://glitch.com/~wm2-probablistic-revenue-share)

### README files
* Update the intro paragraph to something like, "Web Monetization is an API that allows websites to automatically and passively receive payments from web monetized visitors." Something short and less Coil-y.
* In places where we mention or define payment pointers, ensure the references are changed from payment pointer to Open Payments-enabled wallet account or just wallet account (whichever makes the most sense in the given context)
* Update the guide name and URL under Additional References (latest doc revisions may have caused the page name and URL to change)
* In places where a file is described, ensure the description is current. If the file is using an old/unsupported WM event/attribute (like monetizationstart), call it out and describe why it's being used.  
* Don't duplicate information that's already in a guide unless its absolutely necessary (so we don't have to make updates in multiple places if/when things change)

### Functional files
* Use `https://` instead of `$`.
* Update wallet address examples, as needed, to use `subdomain.example.com`. So, `wallet.example.com/alice`.
* In general, and whenever possible, the Glitch example should match the example(s) in the related guide. **Note:** On Aug 28, we decided to use `example.com` instead of `.example` for example payment pointers. After the Glitch updates are finished, we'll need to go into the WM docs and update all examples there. We're waiting so that the guides can be updated with the wallet addresses used in the Glitch examples.

**Comment by melissahenderson** [comment]
I also noticed that clicking on links in the README (links to webmonetization.org and any guides) open within the Glitch frame.

**Comment by melissahenderson** [comment]
@hajjimo Is this good to close?

**Comment by hajjimo** [comment]
All looks good.
