### ISSUE TITLE
Reword the tagline

### ISSUE THREAD

**Issue by matdehaast** [WICG/webmonetization#43]
@justmoon mentioned
> I think the tagline on webmonetization.org is outdated:
> Web Monetization - A JavaScript browser API which allows the creation of a payment stream from the user agent to the website
Nowadays, it's actually a meta tag with an associated (optional) JavaScript API.

Think we need to come up with a few ideas for the tagline. Problem with mentioning meta tag is that we may go with rel Links instead.

**Comment by uchibeke** [comment]
Some suggestions:

- A JavaScript API that enables payments to be sent from the browser to an Interledger wallet via a payment pointer
- A JavaScript API for sending real-time payments from a browser to a payment pointer in the browser
- A JavaScript API for enabling real-time payment from a user agent to  an Interledger wallet via a payment pointer

**Comment by marcoscaceres** [comment]
Maybe we can drop the "Javascript API" part? The JS part is mostly optional.

**Comment by uchibeke** [comment]
That works too. In context, it's clear that is a JS API without being explicit about it

How do these sound?
- Web Monetization: Enable browser to Interledger wallet payment payments via a pointer in the browser
- Web Monetization: Send real-time payments from a browser to a payment pointer in the browser
- Web Monetization: Real-time payments from a browser to an embedded Interledger payment pointer
- Web Monetization: Real-time payment from a user agent to an Interledger wallet via a payment pointer

**Comment by sublimator** [comment]
WM: Get receipts for Interledger payments configured by a simple HTML tag

Not quite, but something along those lines.

**Comment by marcoscaceres** [comment]
It would be great if there was no jargon in the tag line... in particular, we shouldn't mention things like Interledger, wallets, payment pointers, etc. Ideally, the tag line should be something simple that everyone immediately gets.

**Comment by huijing** [comment]
The tagline is now:

> The Web Monetization API allows websites to automatically and passively receive payments from Web Monetization-enabled visitors.
