### ISSUE TITLE
add channel to other channel affialte passive income form YouTube 

### ISSUE THREAD

**Issue by phuquoc81** [WICG/webmonetization#430]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by phuquoc81** [comment]
Is anyone nó how to do it add your YouTube channel lỉke Phubers to another channel

**Comment by sublimator** [comment]
Oh, back in the day Coil used to have Youtube integration, and you could prove your ownership of a channel, and associate a payment pointer. The Coil extension would "adapt" the youtube page and send money to the associated payment pointer.

Currently there's no WM providers. One should be back online soon apparently (fynboss.app), but I'm not sure if there are any plans for Youtube channel adaptation again.

Thanks

**Comment by sublimator** [comment]
Your user name ? Are you from Phu Quoc (an island near Cambodia right?)
