### ISSUE TITLE
Interledger spec links are broken

### ISSUE THREAD

**Issue by RByers** [WICG/webmonetization#431]
In a few places the spec links to `https://interledger.org/rfcs/0027-interledger-protocol-4/`, but these [links](https://interledger.org/rfcs/0027-interledger-protocol-4/) now 404. Should they be updated to `https://interledger.org/developers/rfcs/interledger-protocol/` perhaps?

**Comment by melissahenderson** [comment]
I'll fix this as part of #426.

**Comment by huijing** [comment]
Closes #426

**Comment by melissahenderson** [comment]
Merge issues occurred and the fix was not added. Reopening this for myself.

**Comment by huijing** [comment]
Closed by https://github.com/WICG/webmonetization/pull/437
