### ISSUE TITLE
Add Spanish Translate

### ISSUE THREAD

**Issue by tw1ttt3r** [WICG/webmonetization#59]
Hi, I would like to contribute with the translation of the documentation into Spanish

**Comment by adrianhopebailie** [comment]
That would be awesome! I think we'd need to update the platform to support that. @melissahenderson WDYT?

**Comment by melissahenderson** [comment]
That's a great idea! I'll talk to some folks over here and see if we can work out the logistics.

**Comment by melissahenderson** [comment]
Unfortunately, we don't currently have the capacity to set up WebMon to support internationalization. Let's leave this open for now though.

**Comment by huijing** [comment]
In order for this to happen, we will need to do a bit of refactoring over how we render our content strings. See https://docusaurus.io/docs/migration/translated-sites#updated-translation-apis
TL:DR, we will need to wrap translatable strings in the `<Translate>` component.

**Comment by prafull904434** [comment]
sir, may i work with this issue ,can you assign to me

**Comment by melissahenderson** [comment]
Closing in favor of issue #401
