### ISSUE TITLE
Parallel use of multiple monetization agents/providers

### ISSUE THREAD

**Issue by novazembla** [WICG/webmonetization#60]
Hello, 

I'm trying to get my head around the question how a user could have make use of several providers at the same time? Ideas of having several to try things out, to build an ecosystem, ... are flying around but I can't see how this would be implemented in practice (asking the users to enable/disable extensions on a per site or global basis seems quite a burden)?

But at the moment it is not clear to me who "owns" the document.monetization object. The first one to create it? Does the extension trump any potential inline code? How would two extensions play nicely together? 

Thank you!

**Comment by adrianhopebailie** [comment]
Ideally the API is provided by the browser and the rules as to which provider is behind it will be up to browsers to decide.

So, in an ideal future I can have multiple providers and configure my browser to use different ones on different origins maybe? (with a default )

**Comment by marcoscaceres** [comment]
Closing as answered.
