### ISSUE TITLE
Track accumulated micropayments?

### ISSUE THREAD

**Issue by SamuelEVicente** [WICG/webmonetization#62]
How can we track the amount of money that has accumulated if the requestId changes on page load?

**Comment by sharafian** [comment]
Web Monetization doesn't provide any kind of long-lived identifier on the user, for privacy reasons. However if the site has some ID associated to the user, for example if they're logged in and have a userId, you can associate micropayment events to that userId on the site's backend. Another option would be to just store the accumulated amount in localstorage

**Comment by marcoscaceres** [comment]
Closing as answered.
