### ISSUE TITLE
RSS Applications

### ISSUE THREAD

**Issue by z0al** [WICG/webmonetization#70]
I recently learned about WM and couldn't help but wonder about how it will affect non-Web applications. 

An interesting example is [RSS](https://en.wikipedia.org/wiki/RSS)-Powered Applications mainly Readers and Podcast Players. I will focus on RSS because it's the most popular but the same applies to [ATOM](https://en.wikipedia.org/wiki/Atom_(Web_standard)) and [JSON Feed](https://jsonfeed.org/).

AFAICT, these Apps should act as a Web Browser and behaves mostly like the same way. However, unlike browsers, these Apps won't execute any JS code.

To my understanding, the website owner would usually utilize the JS API to (potentially along with Server-Side verification) to reward paid users e.g. show/hide content.

To achieve similar experience to the Web. I think we might need to extend RSS schema (a.ka. [RSS Module](https://en.wikipedia.org/wiki/RSS#Modules)) and add some additional metadata but I'm not sure how exactly that will look like.

I'm opening this issue for discussion as someone might have something to share.

**Comment by adrianhopebailie** [comment]
Related to #19

**Comment by da2x** [comment]
Atom has a built-in solution for this: the `link` element. The same element can be used in RSS feeds, e.g. an `atom:link` element (the Atom XMLNS is already commonly included in RSS feeds because its schema contains so many useful elements).

So, pending #19, the solution would be to include a payment pointer link for the whole feed or per feed item. Here's an example:

```
<feed>
  <link rel="monetization" href="https://wallet.example.com/example-website-wallet"/>
  <item>
    <link rel="monetization" href="https://wallet.example.com/author/81"/>
  </item>
</feed>
```

```
<rss xmlns:atom=http://www.w3.org/2005/Atom">
  <channel>
    <atom:link rel="monetization" href="https://wallet.example.com/example-website-wallet"/>
    <entry>
      <atom:link rel="monetization" href="https://wallet.example.com/author/81"/>
    </entry>
  </channel>
</rss>
```

Flattr already uses this model for podcasts.

**Comment by dellagustin** [comment]
Similar discussion is happening at https://github.com/Podcastindex-org/podcast-namespace/issues/132

**Comment by marcoscaceres** [comment]
Agree that link is well suited for this, but we would need to work out the mechanics of how link works... it should probably be using `<html:link>`, as that has well defined resource fetching mechanisms and priv/sec controls.

**Comment by marcoscaceres** [comment]
closing as answered... tl;dr: so long as the RSS reader supports the (X)HTML and understands how to deal with `<link>`s, then this "should work"™️. It really comes down to implementations, but if it's using a browser to render the RSS, then it would work (as least at a spec level).
