### ISSUE TITLE
Dynamically added iframe with monetization is not working

### ISSUE THREAD

**Issue by sorxrob** [WICG/webmonetization#78]
So I have a simple extension that adds an iframe to an active tab via content script and here's the sample code:

**content.js**
```javascript
const iframe = document.createElement("iframe");
iframe.src = chrome.runtime.getURL("iframe.html");
iframe.allow = "monetization";
document.body.appendChild(iframe);
```

**iframe.html**
```html
<html>
  <head>
    <meta
      name="monetization"
      content="$coil.xrptipbot.com/my-pointer"
    />
  </head>
  <body>
    hello world
  </body>
</html>
```
**manifest.json**
```javascript
{
  "name": "Test ext",
  "version": "1.0",
  "manifest_version": 2,
  "content_scripts": [
    {
      "matches": ["<all_urls>"],
      "js": ["content.js"]
    }
  ],
  "web_accessible_resources": ["iframe.html"]
}
```

I have the coil extension installed but it's not getting picked up I guess? The coil extension is still disabled.

When I inspect the page, I can see the `iframe` attached though.

<img width="295" alt="Screen Shot 2020-05-30 at 3 19 05 PM" src="https://user-images.githubusercontent.com/13049130/83322300-010bef00-a289-11ea-99fa-0fe80ab9d151.png">

Any idea?

UPDATE:

Also tried in a static page with iframe

```html
<html lang="en">
  <head>
    <title>Test</title>
  </head>
  <body>
    <iframe
      src="iframe.html"
      width="300"
      height="300"
      frameborder="0"
      allow="monetization"
    ></iframe>
  </body>
</html>
```
It's picked up by the coil extension but is not streaming payments.

**Comment by sublimator** [comment]
Are iframes monetized in a static page for you ?

**Comment by sublimator** [comment]
I suspect that the iframe window may not have the Coil extension content script being run in it given it's a `chrome-extension://` url ? 

What is your goal with all this anyway?

**Comment by sorxrob** [comment]
> I suspect that the iframe window may not have the Coil extension content script being run in it given it's a `chrome-extension://` url ?
> 
> What is your goal with all this anyway?

Updated my post regarding the static page test. It's getting picked up by coil extension but is not sending payments.

My goal is to add a payment counter in a Web-Monetized page by attaching an element with a hidden iframe in it so this way the developer can have payments too.

I'm planning to add it as a feature to [this](https://coil.com/p/wobsoriano/Tracking-your-micropayments/opSkSMY2y).

**Comment by sublimator** [comment]
I don't think the Coil content script works for file:// urls either.
Have you tried viewing your html tree entry point file via a http://localhost url? i.e. using a server?

**Comment by sorxrob** [comment]
> I don't think the Coil content script works for file:// urls either.
> Have you tried viewing your html tree entry point file via a http://localhost url? i.e. using a server?

It is running in a server (VS Code Live Server). I tried adding the monetization tag to the static page itself and it's working.

**Comment by sublimator** [comment]
Your payment pointer hasn't been left <redacted> to "$coil.xrptipbot.com/my-pointer"?

**Comment by sublimator** [comment]
I just made sure to install Coil extension from chrome store and checked a page with iframes and it seems to be working for me. You should be able to at least get a static html tree working. 

I suspect `file://` and `chrome-extension://` may not be monetized

**Comment by sorxrob** [comment]
> Your payment pointer hasn't been left `<redacted>` to "$coil.xrptipbot.com/my-pointer"?

Yep. My pointer is fine. Anyway, will try to debug. Thanks!

**Comment by sorxrob** [comment]
Closing this one. It is working indeed.

I forgot to add the event handler that's why I'm not seeing any progress. lol.
