### ISSUE TITLE
Labeling the tools available beyond logos

### ISSUE THREAD

**Issue by cyberdees** [WICG/webmonetization#94]
Within the tools section — it would be super handy if the Tool logo + WM logo have some text and context to what they are. It’s not very accessible as it stands.

**Comment by fruehle** [comment]
Suggested layout
![image](https://user-images.githubusercontent.com/19295116/86046177-c24d8e00-ba1a-11ea-8ecb-759ec946fe2c.png)

**Comment by cyberdees** [comment]
That looks pretty good to me. Nice work!

**Comment by adrianhopebailie** [comment]
Thanks @fruehle!
Here's the link to the design on Figma, anyone in the community interested in trying to implement this change?

We'd need to update the format of the data in [siteConfig.js](https://github.com/WICG/webmonetization/blob/master/website/siteConfig.js#L4-L69) to include some of the new text elements and also adjust the styles so they work as an alphabetical sorted two column grid which becomes one column on mobile.

**Comment by fruehle** [comment]
The link to the figma is [here](https://www.figma.com/file/TDcnc5WL2k9QFHYJZB4Eu1/WebMonetization.org?node-id=211%3A86)

I also made a suggestion for the Browser section. I used the same layout for that to keep the scope of work smaller. Feel free to comment on it.
