### ISSUE TITLE
Prevent monetisation hijacking by allowing authors to define pointers that can be set

### ISSUE THREAD

**Issue by drsm79** [WICG/webmonetization#96]
The example in https://webmonetization.org/docs/probabilistic-rev-sharing is a nice way to share revenues, and I can see other similar modes relying on JS code changing the meta tag (e.g. a platform gets the first second of revenue, then switches to the producer). 

However, this seems trivially open to attack - if I can get some JS onto your pge, I can set the meta tag to be what I want. This is possibly worse in the case where this is done to an unknowing producer (e.g. I put the tag on your site, and you've never heard of web monetisation).

I think two things should be enabled to address this:

1. if a meta tag is present, you can only chnge the pointer to predefined (in the tag) pointers e.g. `<meta name="monetization" content="my_pointer" pointers="your_pointer; her_pointer; his_pointer">` (or something better...)

2. if no `<meta name="monetization" ...>` is present I shouldn't be able to add one, or it should be ignored if I do.

**Comment by sharafian** [comment]
This would cause difficulties for apps that need to add payment pointers dynamically, for instance coil.com's blogging platform or cinnamon.video's video sharing site. Users can configure their payment pointers so requiring a static set of approved payment pointers to be defined wouldn't be able to cover all the users.

I agree that this is a potential attack vector though, at least giving more incentive to attack a site with XSS. Right now we're limited in what we can implement with the extension, but specifying the monetization tag via a header would prevent that avenue of attack. Javascript can't change the headers the page was loaded with, so if the page was loaded with a Web Monetization header it would be locked in. You could still do probabilistic revenue sharing in this case by having the server reply with a random WM header based on the revshare.

Discussion of a WM header has been discussed a little bit in our link vs. meta tag discussion here: https://github.com/WICG/webmonetization/issues/19

**Comment by drsm79** [comment]
Agreed that it'd make certain use cases harder, though a header may be awkward for people who don't own their platform to implement, too. Presumably if sites like coil & cinnamon  can add a header they can render the meta tag server side, and would be able to render `<metaname  name="monetization" content="first_pointer" pointers="second_pointer">`.  Or is the problem there that lots is happening browser side (I've not looked under the covers...)?

How about an optional attribute, so if set either I can't change the value of the meta, or can only change it to one of the values in the attribute, but if it's not there the behaviour is as now?

So you'd have

1. no tag -> can't add it in (or ignored if added)
2. tag without `pointers` -> as now
3. tag with `pointers` -> allow changes to pointers in the list
4. possibly tag with something like `nochange` -> prevent chaning the pointer (could be redundant with a `pointers` of the original tag)

Going slightly further down the rabbit hole... does the plugin ignore things in iframes or similar?

**Comment by kamranayub** [comment]
I think using CSP would be the way to go: https://github.com/WICG/webmonetization/issues/29

CSP generation can be done on the server (to make it dynamic) as a HTTP header and still allows static sites with a [meta tag](https://developers.google.com/web/fundamentals/security/csp#the_meta_tag)

**Comment by drsm79** [comment]
Yeah, that would be nice - I'll close this in preference to #29
