### ISSUE TITLE
Reword motivation

### ISSUE THREAD

**Issue by matdehaast** [WICG/webmonetization#97]
Currently the Motivation section is really adversarial. We should reword this. Some online feedback was 
>  Without a concise and fact-based description of what constitutes "corrupt business models", I think they ought to avoid mentioning "corruption" entirely; it does not really serve a useful purpose. 

@melissahenderson @adrianhopebailie @sharafian can you coordinate to fix this?

**Comment by sharafian** [comment]
The section in question, for context:

> The ability to transfer money has been a long-standing omission from the web platform. As a result, the web suffers from a flood of advertising and corrupt business models. Web Monetization provides an open, native, efficient, and automatic way to compensate creators, pay for API calls, and support crucial web infrastructure.

maybe change 'and corrupt business models' to ', sacrificing user experience and privacy'?

**Comment by melissahenderson** [comment]
What do you think about changing it around so that it's the user that experiences the results, rather than the web? Something like:

As a result, users sacrifice their privacy, suffer from a flood of advertising, and endure poor user experiences.

**Comment by sublimator** [comment]
writer!

**Comment by melissahenderson** [comment]
If you want to get really crazy, you could use some of this from an old Coil blog post.

The Web today is suffering from the symptoms of a broken business model. Every day, we read a new headline about privacy abuses related to ads, demonetization to appease advertisers, unethical sponsored content, popular sites struggling to make money, ads placed next to content without the creator’s consent, adblocker arms race, subscription fatigue, large platforms abusing their market power, and so on. All of these issues can be traced back to one simple problem: browsers don’t pay. This forces sites to raise funds through workarounds like ads, data trafficking, sponsored content, and site-by-site subscriptions.

**Comment by marcoscaceres** [comment]
Pragmatically, WM doesn't in itself solve these issues: one can still do "bad things" listed above and be web-monetized. We should probably avoid calling out what bad practices, and focus on what WM can enable (easy-to-use, privacy-preserving mechanism that enable sites to receive micropayments).
